### ISSUE TITLE
Add shortcut key for page action

### ISSUE THREAD

**Issue by rajatgoyal715** [rajatgoyal715/Mapper#1]
There should be a shortcut key which can do the page action.
Eg. Ctrl + Shift + A may directly open the popup.

https://developer.chrome.com/apps/commands might be useful as a reference.

**Comment by matankb** [comment]
I'd be happy to take a go at this one.

**Comment by matankb** [comment]
It seems like it's [not possible to pragmatically open the page action](https://stackoverflow.com/questions/5544256/chrome-extensionhow-to-pragmatically-open-the-popup-window-from-background-htm/5576816#5576816). However, it is possible to open a popup with the popup.html page. Would this be ok?

**Comment by rajatgoyal715** [comment]
Hi @matankb 
Yes, the command should open the popup.html page.
And maybe, we can add a default value in `value` input box if the command is pressed when some text is selected.

**Comment by rajatgoyal715** [comment]
Closing this issue as the work is done in 27df549cffaf79a7a2cc4bddda13574ca479fbe9
