### ISSUE TITLE
Add option to copy value of an item

### ISSUE THREAD

**Issue by rajatgoyal715** [rajatgoyal715/Mapper#2]
Add a copy icon at the end of the value of every item which will copy the value on clicking.

https://www.w3schools.com/howto/howto_js_copy_clipboard.asp might be helpful as a reference.

**Comment by delete** [comment]
I can help with this. :D

**Comment by delete** [comment]
Hey @rajatgoyal715 , do you really want an icon to copy the item? Wouldn't be cleaner if the copy just happens when the row is clicked? Then the **message()** will give the feedback message.
![print](https://user-images.githubusercontent.com/434694/46586704-7265b100-ca58-11e8-8bd4-c247848c6981.jpg)

**Comment by rajatgoyal715** [comment]
@delete An icon would be more descriptive and it will also reduce the chances of copying by mistake.

**Comment by rajatgoyal715** [comment]
@delete Thanks for the contribution!
Closing this issue as it is done in pull request #5
