### ISSUE TITLE
Add option to delete/remove an item

### ISSUE THREAD

**Issue by rajatgoyal715** [rajatgoyal715/Mapper#3]
Include an icon at the front of the item which upon clicking will remove the item from the chrome storage and thus from the items list.

https://stackoverflow.com/questions/17927378/chrome-storage-sync-remove-array-doesnt-work might be helpful as a reference.

**Comment by Taiters** [comment]
Happy to have a go at this

**Comment by rajatgoyal715** [comment]
@Taiters Thanks for your contribution :smile:
