### ISSUE TITLE
Improve screenshots

### ISSUE THREAD

**Issue by rajatgoyal715** [rajatgoyal715/Mapper#7]
Maybe add frames to screenshots.

https://mockuphone.com/macbookgrey might be helpful.

**Comment by brentrobbins** [comment]
@rajatgoyal715 I am on it.

**Comment by brentrobbins** [comment]
Hi @rajatgoyal715 just create the PR #10 for this issue. Let me know if you need anything else.

**Comment by rajatgoyal715** [comment]
Solved in 87c4bd5136853660af6ba130afc9557f5d5aa8f1
